INSERT INTO Genre (GenreID, Name) VALUES(0, 'Accounting'),
(1, 'Anthropology'),
(2, 'Art'),
(3, 'Autobiography'),
(4, 'Biography'),
(5, 'Biology'),
(6, 'Business'),
(7, 'Chemistry'),
(8, 'Childrens'),
(9, 'Comics'),
(10, 'Computer Science'),
(11, 'Consulting'),
(12, 'Cooking'),
(13, 'Criminal Justice'),
(14, 'Customer Service'),
(15, 'Dance'),
(16, 'Dentistry'),
(17, 'Drama'),
(18, 'Economics'),
(19, 'Education'),
(20, 'Engineering'),
(21, 'Entrepreneurship'),
(22, 'Fantasy'),
(23, 'Fiction'),
(24, 'Film'),
(25, 'Finance'),
(26, 'Fitness'),
(27, 'Geography'),
(28, 'Graphic Novel'),
(29, 'Health'),
(30, 'History'),
(31, 'Horror'),
(32, 'Human Resources'),
(33, 'Information Technology'),
(34, 'Innovation'),
(35, 'Journalism'),
(36, 'Law'),
(37, 'Leadership'),
(38, 'Literature'),
(39, 'Logistics'),
(40, 'Management'),
(41, 'Marketing'),
(42, 'Mathematics'),
(43, 'Medicine'),
(44, 'Music'),
(45, 'Mystery'),
(46, 'Non-Fiction'),
(47, 'Nursing'),
(48, 'Operations'),
(49, 'Pharmacy'),
(50, 'Philosophy'),
(51, 'Physics'),
(52, 'Poetry'),
(53, 'Political Science'),
(54, 'Politics'),
(55, 'Psychiatry'),
(56, 'Psychology'),
(57, 'Radio'),
(58, 'Religion'),
(59, 'Romance'),
(60, 'Sales'),
(61, 'Science'),
(62, 'Science Fiction'),
(63, 'Self-Help'),
(64, 'Sociology'),
(65, 'Spirituality'),
(66, 'Sports'),
(67, 'Strategy'),
(68, 'Supply Chain'),
(69, 'Technology'),
(70, 'Television'),
(71, 'Theatre'),
(72, 'Theology'),
(73, 'Thriller'),
(74, 'Travel'),
(75, 'Veterinary'),
(76, 'Young Adult');

