INSERT INTO Genre (Name, Description, Genre_ID) VALUES('Accounting', 'The suggest worry season evening later.', 0),
('Anthropology', 'Picture south pick hair.', 1),
('Art', 'Age month accept behavior produce list throw.', 2),
('Autobiography', 'Might perhaps hundred sport network work interesting.', 3),
('Biography', 'Evening money yourself I beyond face.', 4),
('Biology', 'Attack we else night fund door after provide.', 5),
('Business', 'Again management seem name record.', 6),
('Chemistry', 'Choice compare method position.', 7),
('Childrens', 'Man number order country once deep tax.', 8),
('Comics', 'Reflect probably approach young people better.', 9),
('Computer Science', 'Knowledge morning nothing back require produce.', 10),
('Consulting', 'Strategy all evidence role manage pull.', 11),
('Cooking', 'Child main huge red another him able.', 12),
('Criminal Justice', 'Data quality training finish.', 13),
('Customer Service', 'Yeah anyone perform carry take produce put.', 14),
('Dance', 'Part because expect color since both begin parent.', 15),
('Dentistry', 'Music practice pass explain ground onto.', 16),
('Drama', 'Lose despite Republican especially develop past network.', 17),
('Economics', 'Another project order want mouth anything trouble.', 18),
('Education', 'Might forward meeting agency focus.', 19),
('Engineering', 'When budget part we policy.', 20),
('Entrepreneurship', 'Will care arm.', 21),
('Fantasy', 'While within we care.', 22),
('Fiction', 'Citizen positive game sometimes glass as office.', 23),
('Film', 'Item onto event would Republican learn eye.', 24),
('Finance', 'Management enjoy fire recognize.', 25),
('Fitness', 'Book argue physical her machine.', 26),
('Geography', 'City consider candidate between between respond sometimes.', 27),
('Graphic Novel', 'Matter finish who understand quickly.', 28),
('Health', 'Enter first increase doctor.', 29),
('History', 'Shoulder pay law stand.', 30),
('Horror', 'Name again serious black remain involve.', 31),
('Human Resources', 'Even small know consumer order poor.', 32),
('Information Technology', 'Reality suddenly Republican official.', 33),
('Innovation', 'Church few so take light relate energy others.', 34),
('Journalism', 'Much she ago skill.', 35),
('Law', 'Experience already give age.', 36),
('Leadership', 'Certainly around half note similar idea.', 37),
('Literature', 'Senior able only trial sing.', 38),
('Logistics', 'Vote door likely information easy listen other.', 39),
('Management', 'Condition near bed during.', 40),
('Marketing', 'About together help when than rule need.', 41),
('Mathematics', 'Individual trial worker different point dinner participant.', 42),
('Medicine', 'Laugh interview color bring Mrs investment science.', 43),
('Music', 'Rate use stop save environmental environmental.', 44),
('Mystery', 'Catch office force girl hit your.', 45),
('Non-Fiction', 'Consumer threat whole new senior western difference thought.', 46),
('Nursing', 'Marriage career fine away.', 47),
('Operations', 'Approach friend decide.', 48),
('Pharmacy', 'Find loss contain his water serve front.', 49),
('Philosophy', 'Glass expect manage yourself service quality this.', 50),
('Physics', 'Red attorney human impact job care.', 51),
('Poetry', 'Same such just page enjoy.', 52),
('Political Science', 'Pull current actually bit call several case here.', 53),
('Politics', 'Nation deep with thing cell structure although art.', 54),
('Psychiatry', 'Move Mr message student.', 55),
('Psychology', 'Foreign assume interview friend buy.', 56),
('Radio', 'Executive enjoy response president growth.', 57),
('Religion', 'Course couple black place paper.', 58),
('Romance', 'Culture tough which.', 59),
('Sales', 'Parent model town beat control Mrs wind act.', 60),
('Science', 'Foreign ok never hit take allow.', 61),
('Science Fiction', 'My little sing cause according with wish capital.', 62),
('Self-Help', 'Identify summer sea watch.', 63),
('Sociology', 'Economic view list feeling song.', 64),
('Spirituality', 'Interesting state character if may action over.', 65),
('Sports', 'Where television our why then reason.', 66),
('Strategy', 'Thank life his will.', 67),
('Supply Chain', 'Year turn bed under lot positive.', 68),
('Technology', 'Art series move run among.', 69),
('Television', 'Amount history bed.', 70),
('Theatre', 'Nice together generation anything.', 71),
('Theology', 'Yet everything reveal its those guess customer.', 72),
('Thriller', 'Unit central know Mr Democrat.', 73),
('Travel', 'Attorney player skin some accept.', 74),
('Veterinary', 'Responsibility property pick apply.', 75),
('Young Adult', 'Section business wall.', 76);

