INSERT INTO Country (CountryID, Name) VALUES(0, 'USA'),
(1, 'Canada'),
(2, 'Mexico'),
(3, 'Brazil'),
(4, 'Argentina'),
(5, 'Chile'),
(6, 'UK'),
(7, 'Germany'),
(8, 'France'),
(9, 'Italy'),
(10, 'Spain'),
(11, 'Russia'),
(12, 'China'),
(13, 'Japan'),
(14, 'India'),
(15, 'Australia'),
(16, 'South Africa'),
(17, 'Nigeria'),
(18, 'Egypt'),
(19, 'Saudi Arabia'),
(20, 'Iran'),
(21, 'South Korea'),
(22, 'North Korea'),
(23, 'Uzbekistan');

